### ISSUE TITLE
change event not working

### ISSUE THREAD

**Issue by xxBedy** [johnthad/paper-tristate-checkbox#2]
<paper-tristate-checkbox on-change="filterChanged($event)">Sample</paper-tristate-checkbox> doesn't fire event.

Original <paper-checkbox on-change="filterChanged($event)"> Sample </paper-checkbox> works as expected.

**Comment by johnthad** [comment]
Thanks. On first glance, I think that the changed event in `<paper-checkbox>` comes from `Polymer.PaperCheckedElementBehavior`, which I expressly did _not_ include because it is two-state, not tristate. That's one reason that this widget isn't derived from `<paper-checkbox>`. `Polymer.PaperCheckedElementBehavior` in turn uses `Polymer.IronCheckedElementBehavior`, also two-state. Hm... I got pulled off Polymer-type stuff shortly after I wrote this. There seems to be a lot added since Polymer 1.3. I'll see what I can do. In the meantime contributions are welcome.
